language: generic 
sudo: required 
services: 
  - docker

before_install:
  - docker build -t sheraz24/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true sheraz24/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-1-725331554838"
  bucket-path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  